import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/components/ContextApi";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "MITS-DU Internship & Placement Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
     <head>
        <link rel="manifest" href="./manifest.json" />
        <link rel="icon" href="./smallico.png" />
      </head>
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <ContextProvider>
           <Toaster />
        {children}
         <div >
                <Footer />
            </div>
        </ContextProvider>
      </body>
    </html>
  );
}
